apiVersion: v1
kind: Secret
metadata:
  name: demo-parent-gitops
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: "git"
  url: "https://github.com/dmfrey/demo-parent-gitops.git"
