apiVersion: v1
kind: Secret
metadata:
  name: docker
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: "helm"
  url: "registry-1.docker.io"
  enableOCI: "true"